default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: belch_development

test:
  <<: *default
  database: belch_test

production:
  <<: *default
  database: belch_production
  username: belch
  password: <%= ENV['BELCH_DATABASE_PASSWORD'] %>
